import Head from "next/head";
import TopNav from "./topNav";
import { Container } from "@mui/material";

function Footer() {
  return <></>;
}

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <TopNav />
      <Container maxWidth="xl">
        <main>{children}</main>
      </Container>
      <Footer />
    </>
  );
}

export default Layout;
