import Head from "next/head";
import TopNav from "./topNav";
import { Container } from "@mui/material";

function Footer() {
  return <footer>Powered by Tommy Kwok</footer>;
}

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TopNav />
      <Container maxWidth="xl">
        <main>{children}</main>
      </Container>
      <Footer />
    </>
  );
}

export default Layout;
